# Generated by Django 4.2.1 on 2023-08-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('gallary', models.TextField(default='')),
            ],
        ),
    ]
