# Generated by Django 4.2.1 on 2023-08-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('gpa', models.CharField(max_length=100)),
                ('badge', models.CharField(max_length=100)),
                ('degrees', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
