# Generated by Django 4.2.1 on 2023-08-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('gallary', models.ImageField(default='', upload_to='experience/images')),
                ('urls', models.URLField(default='')),
                ('skills', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
