# Generated by Django 4.2.1 on 2023-08-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='subtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
