# Generated by Django 4.2.1 on 2023-09-06 18:47

from django.db import migrations, models
import experience.models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_alter_experience_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='gallary',
            field=models.ImageField(blank=True, null=True, upload_to=experience.models.upload_to),
        ),
    ]
