# Generated by Django 4.2.1 on 2023-09-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_alter_experience_gallary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company',
        ),
    ]
