# Generated by Django 4.2.1 on 2023-09-11 19:29

from django.db import migrations, models
import django.db.models.deletion
import experience.models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_remove_experience_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='gallary',
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=experience.models.upload_to)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='experience.experience')),
            ],
        ),
    ]
